services:
  - type: web
    name: oasis-community-map
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        generateValue: true
      - key: GOOGLE_SHEETS_ID
        sync: false
      - key: GOOGLE_SERVICE_ACCOUNT_EMAIL  
        sync: false
      - key: GOOGLE_PRIVATE_KEY
        sync: false
    autoDeploy: true
    branch: main 